main/urls.py
from django.urls import path
from . import views
from .apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
   path('', views.MainListView.as_view(), name='home'),
   path('create/channel/', views.СhannelCreateView.as_view(), name='create_channel'),
   path('update/channel/<int:pk>', views.СhannelUpdateView.as_view(), name='update_channel'),
   path("channel/<str:channel_name>/", views.СhannelDetailView.as_view(), name='detail'),
]

post/urls.py
from django.urls import path
from . import views
from .apps import PostConfig

app_name = PostConfig.name

urlpatterns = [
   path('create/post/', views.PostCreateView.as_view(), name='create_post'),
   path("update/post/<int:pk>", views.PostUpdateView.as_view(), name='update_post'),
   path("delete/post/<int:pk>", views.PostDeleteView.as_view(), name='delete_post'),
   path('create/comments/<int:post_id>/', views.СommentsCreateView.as_view(), name='create_comm'),
   path("delete/comments/<int:pk>", views.СommentsDeleteView.as_view(), name='delete_comm'),
   path("update/comments/<int:pk>", views.СommentsUpdateView.as_view(), name='update_comm'),
   path('update-likes/<int:post_id>/', views.UpdateLikesView.as_view(), name='update_likes'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("main.urls")),
    path("payment/", include("payment.urls")),
    path("", include("subscription.urls")),
    path("", include("post.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from main.models import Сhannel
from subscription.models import Subscriptions

NULLABLE = {'null': True, 'blank': True}


class Post(models.Model):
    name = models.CharField(max_length=70, verbose_name='Название поста')
    photo_post = models.ImageField(upload_to='post/', verbose_name='фотография к посту', **NULLABLE)
    description = models.TextField(verbose_name='Описание поста', **NULLABLE)
    subscription_level = models.ForeignKey(Subscriptions, on_delete=models.SET_NULL, **NULLABLE)
    likes = models.IntegerField(verbose_name='Кол-во лайков', **NULLABLE, default=0)
    time_the_comment = models.DateTimeField(verbose_name='Дата отправки поста')
    channel = models.ForeignKey(Сhannel, on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.description} {self.subscription_level}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('name',)


class Сomments(models.Model):
    user = models.CharField(max_length=70, verbose_name='Nickname пользователя')
    description = models.TextField(verbose_name='Комментарий')
    time_the_comment = models.DateTimeField(verbose_name='Дата отправки комментария')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f'{self.user} {self.description}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('user',)

subscription/models.py
from django.db import models
from subscription.validators import min_sum, validate_non_negative

NULLABLE = {'null': True, 'blank': True}


class Subscriptions(models.Model):
    name = models.CharField(max_length=15, verbose_name='Название Подписки')
    description = models.CharField(max_length=55, verbose_name='Описание Подписки')
    strength_of_subscription = models.IntegerField(verbose_name='Чем выше число, тем сильнее подписка', validators=[validate_non_negative])
    amount_per_month = models.IntegerField(verbose_name='Сумма за месяц', validators=[min_sum])
    channel = models.ForeignKey('main.Сhannel', on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.description} {self.amount_per_month}'

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ('name',)

post/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.urls import reverse
from post.models import Post, Сomments
from post.permissions import AuthorCommentPermissionsMixin, AuthorPostPermissionsMixin
from django.views import View
import datetime


@method_decorator(login_required, name='dispatch')
class PostCreateView(CreateView):
    fields = '__all__'
    model = Post
    template_name = 'post/create_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        moscow_time = timezone.now() + datetime.timedelta(hours=3)
        current_date = timezone.now().date()
        formatted_date = current_date.strftime('%Y-%m-%d')
        context['time'] = moscow_time.time()
        context['date'] = formatted_date
        return context

    def get_success_url(self) -> str:
        return reverse('main:detail', args=[self.object.channel.name])


@method_decorator(login_required, name='dispatch')
class PostUpdateView(AuthorPostPermissionsMixin, UpdateView):
    fields = '__all__'
    model = Post
    template_name = 'post/edit_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        moscow_time = timezone.now() + datetime.timedelta(hours=3)
        current_date = timezone.now().date()
        formatted_date = current_date.strftime('%Y-%m-%d')
        context['time'] = moscow_time.time()
        context['date'] = formatted_date
        return context

    def get_success_url(self) -> str:
        return reverse('main:detail', args=[self.object.channel.name])


@method_decorator(login_required, name='dispatch')
class PostDeleteView(AuthorPostPermissionsMixin, DeleteView):
    model = Post

    def get_success_url(self) -> str:
        return reverse('main:detail', args=[self.object.channel.name])

# -----------------------------------------------------------------------------------


@method_decorator(login_required, name='dispatch')
class СommentsCreateView(CreateView):
    fields = '__all__'
    model = Сomments
    template_name = 'post/create_comments.html'

    def get_success_url(self) -> str:
        return reverse('main:detail', args=[self.object.post.channel.name])

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        form.instance.post = post
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_id = self.kwargs['post_id']
        post = get_object_or_404(Post, pk=post_id)
        context['post_my'] = post
        moscow_time = timezone.now() + datetime.timedelta(hours=3)
        current_date = timezone.now().date()
        formatted_date = current_date.strftime('%Y-%m-%d')
        context['time'] = moscow_time.time()
        context['date'] = formatted_date
        return context


@method_decorator(login_required, name='dispatch')
class СommentsDeleteView(AuthorCommentPermissionsMixin, DeleteView):
    model = Сomments

    def get_success_url(self) -> str:
        return reverse('main:detail', args=[self.object.post.channel.name])


@method_decorator(login_required, name='dispatch')
class СommentsUpdateView(AuthorCommentPermissionsMixin, UpdateView):
    model = Сomments
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        moscow_time = timezone.now() + datetime.timedelta(hours=3)
        current_date = timezone.now().date()
        formatted_date = current_date.strftime('%Y-%m-%d')
        context['time'] = moscow_time.time()
        context['date'] = formatted_date
        return context

    def get_success_url(self) -> str:
        return reverse('main:detail', args=[self.object.post.channel.name])

# ----------------------------------------------------------------------------


@method_decorator(login_required, name='dispatch')
class UpdateLikesView(View):
    template_name = 'post/update_likes.html'

    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, pk=post_id)

        user_likes_key = f"user_likes_{post_id}"
        user_likes = request.session.get(user_likes_key, 0)

        if user_likes == 0:
            post.likes += 1
            post.save()

            request.session[user_likes_key] = 1
        else:
            post.likes -= 1
            post.save()

            request.session[user_likes_key] = 0

        redirect_url = reverse('main:detail', args=[post.channel.name])
        return render(request, self.template_name, {'redirect_url': redirect_url})

post/templates/post/create_comments.html
{% extends 'main/base.html' %}     
{% block content %}
<style>
  .red{
     background-color: rgb(255, 0, 0);
     color: #fefefe;
     height: 25px;
     width: 530px;
   }
  .MMMM:hover {
  transform: scale(1.1);
  background-color: rgb(48, 193, 0);
  color: rgb(255, 255, 255);
  }
 </style>

<form class="form-signin" method="POST" enctype="multipart/form-data" >
   {% csrf_token %}
   <a class="btn btn-warning" href="http://127.0.0.1:8000/channel/{{ post_my.channel.name }}">Отмена</a>
   <h1 class="h3 mb-3 font-weight-normal">Написать комментарий, для поста: {{ post_my.name }}
   </h1>
     <div class="form-group">
       <br>
       <input type="hidden" name="user" value="{{ request.user.nickname }}">
       {% if form.user.errors %}
         <ul class="errorlist">
           {% for error in form.user.errors %}
             
             <li class="red">{{ error }} Укажите ваш nickname в настройках</li>
           {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
       {{ form.description.label_tag }}
       <br>
       {{ form.description }}
       {% if form.description.errors %}
         <ul class="errorlist">
           {% for error in form.description.errors %}
             <li class="red">{{ error }}</li>
           {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
      {{ form.time_the_comment.label_tag }}
      <br>
      <input type="datetime" name="time_the_comment" class="form-control" id="inputWarning1" value="{{ date }} {{ time }}" readonly>
      {% if form.time_the_comment.errors %}
         <ul class="errorlist">
            {% for error in form.time_the_comment.errors %}
               <li class="red">{{ error }}</li>
            {% endfor %}
         </ul>
      {% endif %}
  </div>
   <div class="form-group">
      <input type="hidden" name="post" value="{{ post_my.pk }}">
    </div>
   <div class="checkbox mb-3">
     <a href="/">Выйти</a>
   </div>
   <button class="btn btn-lg btn-success" type="submit">Сохранить</button>
 </form>
{% endblock %}

post/templates/post/create_post.html
{% extends 'main/base.html' %}     
{% block content %}
<style>
  .red{
     background-color: rgb(255, 0, 0);
     color: #fefefe;
     height: 25px;
     width: 490px;
   }
  .MMMM:hover {
  transform: scale(1.1);
  background-color: rgb(48, 193, 0);
  color: rgb(255, 255, 255);
  }
 </style>

<form class="form-signin" method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   <a class="btn btn-warning" href="http://127.0.0.1:8000/channel/{{ request.user.channel.name }}">Отмена</a>
   <h1 class="h3 mb-3 font-weight-normal">Cоздание поста для канала: {{ request.user.channel.name }}
   </h1>
     <div class="form-group">
       {{ form.photo_post.label_tag }}
       <br>
       {% if object.photo_post %}
         <img class="card-img-top" src="{{ object.photo_post.url }}" alt="{{ object.header }}" style="height: 225px; width: 60%; display: block;"/>
       {% endif %}
       {{ form.photo_post }}
       {% if form.photo_post.errors %}
         <ul class="errorlist">
       {% for error in form.photo_post.errors %}
         <li class="red">{{ error }}</li>
       {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
       {{ form.name.label_tag }}
       <br>
       {{ form.name }}
       {% if form.name.errors %}
         <ul class="errorlist">
           {% for error in form.name.errors %}
             <li class="red">{{ error }}</li>
           {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
       {{ form.description.label_tag }}
       <br>
       {{ form.description }}
       {% if form.description.errors %}
         <ul class="errorlist">
           {% for error in form.description.errors %}
             <li class="red">{{ error }}</li>
           {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
      {{ form.subscription_level.label_tag }}
      <br>
      <select name="{{ form.subscription_level.name }}" class="form-control">
        {% if not user.channel.subscriptions_set.all %}
          <option value="">Пост бесплатный (доступен без подписки)</option>
        {% endif %}
        <option value="">Пост бесплатный (доступен без подписки)</option>
        {% for subscription in user.channel.subscriptions_set.all %}
        <option value="{{ subscription.pk }}">{{ subscription.name }} (если купить данную подписку или выше ее. Сила подписки: {{ subscription.strength_of_subscription }} )</option>
        {% endfor %}
      </select>
      {% if form.subscription_level.errors %}
        <ul class="errorlist">
          {% for error in form.subscription_level.errors %}
            <li class="red">{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.time_the_comment.label_tag }}
      <br>
      <input type="datetime" name="time_the_comment" class="form-control" id="inputWarning1" value="{{ date }} {{ time }}" readonly>
      {% if form.time_the_comment.errors %}
        <ul class="errorlist">
          {% for error in form.time_the_comment.errors %}
            <li class="red">{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="form-group">
      <br>
      <input type="hidden" name="channel" value="{{ request.user.channel.id }}">
    </div>
   <div class="checkbox mb-3">
     <a href="/">Выйти</a>
   </div>
   <button class="btn btn-lg btn-success" type="submit">Сохранить</button>
 </form>
{% endblock %}

post/templates/post/edit_post.html
{% extends 'main/base.html' %}     
{% block content %}
<style>
  .red{
     background-color: rgb(255, 0, 0);
     color: #fefefe;
     height: 25px;
     width: 490px;
   }
  .MMMM:hover {
  transform: scale(1.1);
  background-color: rgb(48, 193, 0);
  color: rgb(255, 255, 255);
  }
 </style>

<form class="form-signin" method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   <a class="btn btn-warning" href="http://127.0.0.1:8000/channel/{{ request.user.channel.name }}">Отмена</a>
   <h1 class="h3 mb-3 font-weight-normal">Редактировать поста для канала: {{ request.user.channel.name }}
   </h1>
     <div class="form-group">
       {{ form.photo_post.label_tag }}
       <br>
       {% if object.photo_post %}
         <img class="card-img-top" src="{{ object.photo_post.url }}" alt="{{ object.header }}" style="height: 225px; width: 60%; display: block;"/>
       {% endif %}
       {{ form.photo_post }}
       {% if form.photo_post.errors %}
         <ul class="errorlist">
       {% for error in form.photo_post.errors %}
         <li class="red">{{ error }}</li>
       {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
       {{ form.name.label_tag }}
       <br>
       {{ form.name }}
       {% if form.name.errors %}
         <ul class="errorlist">
           {% for error in form.name.errors %}
             <li class="red">{{ error }}</li>
           {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
       {{ form.description.label_tag }}
       <br>
       {{ form.description }}
       {% if form.description.errors %}
         <ul class="errorlist">
           {% for error in form.description.errors %}
             <li class="red">{{ error }}</li>
           {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
      {{ form.subscription_level.label_tag }}
      <br>
      <select name="{{ form.subscription_level.name }}" class="form-control">
        {% if not user.channel.subscriptions_set.all %}
          <option value="">Пост бесплатный (доступен без подписки)</option>
        {% endif %}
        <option value="">Пост бесплатный (доступен без подписки)</option>
        {% for subscription in user.channel.subscriptions_set.all %}
          <option value="{{ subscription.pk }}">{{ subscription.name }} (если купить данную подписку или выше ее. Сила подписки: {{ subscription.strength_of_subscription }} )</option>
        {% endfor %}
      </select>
      {% if form.subscription_level.errors %}
        <ul class="errorlist">
          {% for error in form.subscription_level.errors %}
            <li class="red">{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.time_the_comment.label_tag }}
      <br>
      <input type="datetime" name="time_the_comment" class="form-control" id="inputWarning1" value="{{ date }} {{ time }}" readonly>
      {% if form.time_the_comment.errors %}
        <ul class="errorlist">
          {% for error in form.time_the_comment.errors %}
            <li class="red">{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="form-group">
      <br>
      <input type="hidden" name="channel" value="{{ request.user.channel.id }}">
    </div>
   <div class="checkbox mb-3">
     <a href="/">Выйти</a>
   </div>
   <button class="btn btn-lg btn-success" type="submit">Сохранить</button>
 </form>
{% endblock %}

post/templates/post/post_confirm_delete.html
{% extends 'main/base.html' %}     
{% block content %}
<div class="col-12">
   <div class="row">
      <div class="col-6">
         <div class="card">
            <div class="card-body">
               <form method="post">
                  {% csrf_token %}
                  <p>Вы точно уверенны что хотите удалить данный пост?
                  <button type="submit" class="btn btn-danger">Подтвердить</button>
                  <a href="/channel/{{ request.user.channel.name }}" class="btn btn-warning">Отмена</a>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

post/templates/post/update_likes.html
{% if redirect_url %}
    <script>
        window.location.href = "{{ redirect_url }}";
    </script>
{% endif %}

post/templates/post/сomments_confirm_delete.html
{% extends 'main/base.html' %}     
{% block content %}
<div class="col-12">
   <div class="row">
      <div class="col-6">
         <div class="card">
            <div class="card-body">
               <form method="post">
                  {% csrf_token %}
                  <p>Вы точно уверенны что хотите удалить данный комментарий?
                  <button type="submit" class="btn btn-danger ">Подтвердить</button>
                  <a href="/channel/{{ object.post.channel.name }}" class="btn btn-warning">Отмена</a>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

post/templates/post/сomments_form.html
{% extends 'main/base.html' %}     
{% block content %}
<style>
  .red{
     background-color: rgb(255, 0, 0);
     color: #fefefe;
     height: 25px;
     width: 530px;
   }
  .MMMM:hover {
  transform: scale(1.1);
  background-color: rgb(48, 193, 0);
  color: rgb(255, 255, 255);
  }
 </style>

<form class="form-signin" method="POST" enctype="multipart/form-data" >
   {% csrf_token %}
   <a class="btn btn-warning" href="http://127.0.0.1:8000/channel/{{ object.post.channel.name }}">Отмена</a>
   <h1 class="h3 mb-3 font-weight-normal">Редактировать комментарий: {{ object.description }}
   </h1>
     <div class="form-group">
       <br>
       <input type="hidden" name="user" value="{{ request.user.nickname }}">
       {% if form.user.errors %}
         <ul class="errorlist">
           {% for error in form.user.errors %}
             <li class="red">{{ error }}</li>
           {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
       {{ form.description.label_tag }}
       <br>
       {{ form.description }}
       {% if form.description.errors %}
         <ul class="errorlist">
           {% for error in form.description.errors %}
             <li class="red">{{ error }}</li>
           {% endfor %}
         </ul>
       {% endif %}
     </div>
     <div class="form-group">
      {{ form.time_the_comment.label_tag }}
      <br>
      <input type="datetime" name="time_the_comment" class="form-control" id="inputWarning1" value="{{ date }} {{ time }}" readonly>
      {% if form.time_the_comment.errors %}
         <ul class="errorlist">
            {% for error in form.time_the_comment.errors %}
               <li class="red">{{ error }}</li>
            {% endfor %}
         </ul>
      {% endif %}
  </div>
   <div class="form-group">
      <input type="hidden" name="post" value="{{ object.post.pk }}">
    </div>
   <div class="checkbox mb-3">
     <a href="/">Выйти</a>
   </div>
   <button class="btn btn-lg btn-success" type="submit">Сохранить</button>
 </form>
{% endblock %}